name: PR Check
on:
  pull_request:
    branches: [ main ]

jobs:
  pr_check:
    name: PR Check
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependency
        run: |
          pip install --upgrage pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest -s tests
